# Generated by Django 4.1.7 on 2023-11-02 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("first_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("second_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("third_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fourth_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fifth_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("first_vel", models.DecimalField(decimal_places=2, max_digits=5)),
                ("second_vel", models.DecimalField(decimal_places=2, max_digits=5)),
                ("third_vel", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fourth_vel", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fifth_vel", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
