# Generated by Django 4.1.7 on 2023-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adrtest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdata",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
